const days=[
{date:'2026-09-10',n:'10',dow:'THU',label:'大阪',title:'抵達大阪',subtitle:'今天的任務只有順利抵達',pins:['關西空港','Aloft 堂島','野口太郎'],events:[{time:'10:15',icon:'✈',title:'JX822 桃園起飛',meta:'TPE T1 → KIX T1 · 14:00 抵達',tag:'FLIGHT'},{time:'16:30',icon:'🏨',title:'Aloft Osaka Dojima',meta:'Check-in · 堂島／北新地',map:'https://www.google.com/maps/search/?api=1&query=Aloft%20Osaka%20Dojima%20Osaka'},{time:'午後',icon:'💻',title:'Remote',meta:'Flexible · 飯店工作'},{time:'晚上',icon:'🍜',title:'野口太郎ラーメン',meta:'貝出汁系 · 北新地 · ¥1,000–1,999',map:'https://www.google.com/maps/search/?api=1&query=%E9%87%8E%E5%8F%A3%E5%A4%AA%E9%83%8E%E3%83%A9%E3%83%BC%E3%83%A1%E3%83%B3%20%E5%8C%97%E6%96%B0%E5%9C%B0%E6%9C%AC%E5%BA%97',tabelog:'https://tabelog.com/osaka/A2701/A270101/27129462/'}]},
{date:'2026-09-11',n:'11',dow:'FRI',label:'藝術',title:'森之宮',subtitle:'Remote＋空間美術館',pins:['Aloft 堂島','森之宮美術館','回転すし さかえ'],events:[{time:'白天',icon:'💻',title:'Remote',meta:'Flexible · 飯店工作'},{transit:'Osaka → 森之宮'},{time:'預約',icon:'🎨',title:'Museum of Spatial Art OSAKA',meta:'千田泰廣 Yasuhiro Chida · 森之宮',tag:'RESERVED',map:'https://www.google.com/maps/search/?api=1&query=Museum%20of%20Spatial%20Art%20OSAKA%20%E6%A3%AE%E4%B9%8B%E5%AE%87'},{transit:'森之宮 → 梅田'},{time:'晚上',icon:'🍣',title:'回転すし さかえ',meta:'阪急東通り · 晚營業 · ¥1,000–1,999',map:'https://www.google.com/maps/search/?api=1&query=%E5%9B%9E%E8%BB%A2%E3%81%99%E3%81%97%20%E3%81%95%E3%81%8B%E3%81%88%20%E9%98%AA%E6%80%A5%E6%9D%B1%E9%80%9A%E3%82%8A%E5%BA%97',tabelog:'https://tabelog.com/osaka/A2701/A270101/27002305/'}]},
{date:'2026-09-12',n:'12',dow:'SAT',label:'宇治',title:'宇治',subtitle:'什麼都不要做太多的一天',pins:['宇治川','喫茶 コンソラ','清次郎'],events:[{time:'睡飽',icon:'🚆',title:'前往宇治',meta:'Osaka → Uji · 不趕時間'},{time:'午後',icon:'☕',title:'宇治自由時間',meta:'宇治川散步 · 喫茶 コンソラ',note:'今天就是來發呆，不設定離開時間。',map:'https://www.google.com/maps/search/?api=1&query=%E5%96%AB%E8%8C%B6%20%E3%82%B3%E3%83%B3%E3%82%BD%E3%83%A9%20%E5%AE%87%E6%B2%BB'},{transit:'約 58 min',tip:'建議 17:50 前離開宇治'},{time:'19:30',icon:'🥩',title:'清次郎 北新地店',meta:'Yakiniku · All-you-can-eat',tag:'RESERVED',map:'https://www.google.com/maps/search/?api=1&query=%E7%82%AD%E7%81%AB%E7%84%BC%E8%82%89%20%E6%B8%85%E6%AC%A1%E9%83%8E%20%E5%8C%97%E6%96%B0%E5%9C%B0%E5%BA%97',tabelog:'https://tabelog.com/osaka/A2701/A270101/27017667/'}]},
{date:'2026-09-13',n:'13',dow:'SUN',label:'奈良',title:'生駒・奈良',subtitle:'踩腳踏車，然後被鹿搶劫',pins:['生駒山','奈良公園','百夜月'],optional:['春日大社','奈良町'],events:[{time:'早上',icon:'🚲',title:'生駒山上遊樂園',meta:'主要目標：サイクルモノレール',map:'https://www.google.com/maps/search/?api=1&query=%E7%94%9F%E9%A7%92%E5%B1%B1%E4%B8%8A%E9%81%8A%E5%9C%92%E5%9C%B0'},{transit:'生駒 → 近鐵奈良'},{time:'午後',icon:'🦌',title:'奈良公園・東大寺',meta:'鹿仙貝 → 東大寺 → 二月堂'},{time:'17:15',icon:'🥢',title:'そば切り 百夜月',meta:'只收現金 · 不接受預約',note:'隔天還有 USJ，不要提前把雙腳報廢。',map:'https://www.google.com/maps/search/?api=1&query=%E3%81%9D%E3%81%B0%E5%88%87%E3%82%8A%20%E7%99%BE%E5%A4%9C%E6%9C%88%20%E5%A5%88%E8%89%AF',tabelog:'https://tabelog.com/nara/A2901/A290101/29000692/'}]},
{date:'2026-09-14',n:'14',dow:'MON',label:'USJ',title:'Universal Studios Japan',subtitle:'今天沒有其他行程',pins:['Universal Studios Japan'],special:true,events:[]},
{date:'2026-09-15',n:'15',dow:'TUE',label:'回家',title:'回家',subtitle:'不要對大阪產生任何觀光野心',pins:['Aloft 堂島','關西空港'],events:[{time:'10:00',icon:'🧳',title:'離開大阪市區',meta:'Check-out · 直接前往關西機場'},{transit:'Osaka → KIX T1'},{time:'13:25',icon:'✈',title:'JX821 關西起飛',meta:'KIX T1 → TPE T1 · 15:20 抵達',tag:'FLIGHT'}]}
];
const app=document.querySelector('#app'),params=new URLSearchParams(location.search),tripStart=new Date('2026-09-10T00:00:00+09:00'),tripEnd=new Date('2026-09-15T23:59:59+09:00'),now=new Date();
const inferredDate=now>=tripStart&&now<=tripEnd?new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo'}).format(now):'2026-09-12';let selectedDate=params.get('date')||inferredDate,currentView=params.get('view')||(now<tripStart?'overview':now<=tripEnd?'day':'overview');
function renderDateRail(){document.querySelector('#dateButtons').innerHTML=days.map(d=>`<button class="date-button ${d.date===selectedDate?'active':''}" data-date="${d.date}" aria-label="${d.n} 日 ${d.label}"><b>${d.n}</b><small>${d.dow}</small><em>${d.label}</em></button>`).join('');document.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{selectedDate=b.dataset.date;currentView='day';syncUrl();render()})}
function syncUrl(){const q=new URLSearchParams;if(currentView!=='day')q.set('view',currentView);if(selectedDate!=='2026-09-12')q.set('date',selectedDate);history.replaceState({},'',`${location.pathname}${q.size?'?'+q:''}`)}
function mapMarkup(day,full=false){return `<div class="${full?'map-full':''}"><div class="map-card"><div class="map-water"></div>${day.pins.map((p,i)=>`<div class="pin" style="left:${18+(i*23)%65}%;top:${18+(i*29)%64}%"><i>${i+1}</i><span>${p}</span></div>`).join('')}</div><div class="map-caption"><span>${day.label.toUpperCase()} · PERSONAL MAP</span><span>${day.pins.length} PLACES</span></div></div>`}
function timelineMarkup(day){return `<div class="timeline-title"><h3>Full day</h3><span>${day.events.filter(e=>e.title).length} EVENTS</span></div><div class="timeline">${day.events.map(e=>e.transit?`<div class="transit"><b>🚆 ${e.transit}</b>${e.tip||''}</div>`:`<article class="event"><time class="event-time">${e.time}</time><h4>${e.icon} ${e.title}</h4><p class="event-meta">${e.meta}</p>${e.tag?`<span class="tag">✓ ${e.tag}</span>`:''}${e.note?`<p class="event-note">${e.note}</p>`:''}<div class="event-links">${e.map?`<a class="directions" href="${e.map}" target="_blank" rel="noreferrer">Google Maps ↗</a>`:''}${e.tabelog?`<a class="directions tabelog" href="${e.tabelog}" target="_blank" rel="noreferrer">食べログ ↗</a>`:''}</div></article>`).join('')}</div>${day.optional?`<section class="optional"><p class="label">IF YOU STILL HAVE ENERGY</p>${day.optional.map(x=>`<p>＋ ${x}</p>`).join('')}</section>`:''}`}
function focusMarkup(day){const list=day.events.filter(e=>e.title),current=list[1]||list[0],next=list[2];if(!current)return'';return `<section class="today-focus"><p class="label">TODAY'S FOCUS</p><div class="now-card"><span class="emoji">${current.icon}</span><div><h3>${current.title}</h3><p>${current.meta}</p>${current.note?`<p class="quote">「${current.note}」</p>`:''}</div></div>${next?`<div class="next-row"><time>${next.time}</time><div><b>NEXT · ${next.title}</b><small>${next.meta}</small></div><span>→</span></div>`:''}</section>`}
function renderDay(){const d=days.find(x=>x.date===selectedDate)||days[0];if(d.special)return `<section class="page"><header class="day-heading"><p class="eyebrow">${d.dow} · SEP ${d.n}</p></header><div class="day-layout"><div class="day-column"><section class="usj"><span class="pumpkin">🎃</span><p class="all-day">HALLOWEEN · ALL DAY</p><h3>UNIVERSAL<br>STUDIOS JAPAN</h3><p>今天沒有其他行程。</p><a class="directions" href="https://www.google.com/maps/search/?api=1&query=Universal%20Studios%20Japan" target="_blank">OPEN MAP ↗</a><blockquote>晚上唯一判斷標準：<br>「我還活著嗎？」</blockquote></section></div><aside class="map-column"><div class="sticky-map">${mapMarkup(d)}</div></aside></div></section>`;return `<section class="page"><div class="day-layout"><div class="day-column"><header class="day-heading"><p class="eyebrow">${d.dow} · SEP ${d.n}</p><h2>${d.title}<span>${d.subtitle}</span></h2></header>${focusMarkup(d)}${timelineMarkup(d)}</div><aside class="map-column"><div class="sticky-map">${mapMarkup(d)}</div></aside></div></section>`}
function renderOverview(){return `<section class="page overview"><header class="overview-hero"><h2>大阪・宇治<br><span>奈良</span></h2><p class="count">SEP 10 — SEP 15<br>6 DAYS · JAPAN</p></header><section class="overview-block"><p class="label">FLIGHTS</p><div><div class="flight-row"><span class="flight-code">JX822</span><div><strong>TPE 10:15 → KIX 14:00</strong><p>SEP 10 · THURSDAY</p></div></div><div class="flight-row"><span class="flight-code">JX821</span><div><strong>KIX 13:25 → TPE 15:20</strong><p>SEP 15 · TUESDAY</p></div></div></div></section><section class="overview-block"><p class="label">STAY</p><div class="stay"><h3>⌂ Aloft Osaka Dojima</h3><p>SEP 10 → SEP 15 · DOJIMA, OSAKA</p></div></section><section class="overview-block"><p class="label">ITINERARY</p><div>${days.map(d=>`<div class="day-summary" data-summary-date="${d.date}"><b>${d.n}</b><small>${d.dow}</small><span>${d.title} · ${d.subtitle}</span></div>`).join('')}</div></section></section>`}
function renderReservations(){const items=[['SEP 11','🎨','Museum of Spatial Art','Reserved'],['SEP 12 · 19:30','🥩','清次郎 北新地店','Reserved'],['SEP 14','🎢','Universal Studios Japan','Ticket'],['SEP 10—15','🏨','Aloft Osaka Dojima','Confirmed'],['SEP 10 / 15','✈','JX822 · JX821','Confirmed']];return `<section class="page reservation-list"><header class="day-heading"><p class="eyebrow">ALL IN ONE PLACE</p><h2>Reservations<span>預約與票券</span></h2></header>${items.map(i=>`<article class="reservation-item"><time class="flight-code">${i[0]}</time><span>${i[1]}</span><div><h3>${i[2]}</h3><p>Booking details</p></div><b class="status">✓ ${i[3].toUpperCase()}</b></article>`).join('')}</section>`}
function render(){renderDateRail();const d=days.find(x=>x.date===selectedDate)||days[0];app.innerHTML=currentView==='overview'?renderOverview():currentView==='map'?`<section class="page map-full"><header class="day-heading"><p class="eyebrow">SEP ${d.n} · MY PLACES</p><h2>Map<span>只看這趟旅行的地點</span></h2></header>${mapMarkup(d,true)}</section>`:currentView==='reservations'?renderReservations():renderDay();document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===currentView));document.querySelectorAll('[data-summary-date]').forEach(x=>x.onclick=()=>{selectedDate=x.dataset.summaryDate;currentView='day';syncUrl();render()});app.focus({preventScroll:true})}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{currentView=b.dataset.view;syncUrl();render()});const drawer=document.querySelector('#drawer');document.querySelector('#menuButton').onclick=()=>drawer.showModal();document.querySelector('#closeDrawer').onclick=()=>drawer.close();drawer.addEventListener('click',e=>{if(e.target===drawer)drawer.close()});document.querySelectorAll('[data-drawer-view]').forEach(b=>b.onclick=()=>{currentView=b.dataset.drawerView==='flights'?'overview':b.dataset.drawerView;drawer.close();syncUrl();render()});render();
